name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions  with Dependencies and Intentional FailğŸš€

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Intentionally fail
        run: |
          echo "âŒ Setup failing..."
          exit 1

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "ğŸ› ï¸ You shouldn't see this if setup fails."

  test:
    needs: [build]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Run test step
        run: echo "âœ… Running tests despite failure in setup/build."
